name: JawwadJafri
favicon: null
layout_spectrum: 0.8803201508708298
typography_spectrum: 0.029871803242713213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6441458177287132
  lightness: 0.7536457497626543
  saturation: 0.15480564162135124
  rhythmicContrast: 0.25882704136893153
purpose: []
